name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  Build-Push-Docker-Image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and Push Multi-Architecture Docker Image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/hr-ai-gemini-discord-bot:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/hr-ai-gemini-discord-bot:v2.${{ github.run_number }} \
            --push .

      - name: Tagging Github Commit as per Docker Image Tag.
        run: |
          git tag v2.${{ github.run_number }}
          git push origin v2.${{ github.run_number }}
